/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktikum_2;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */

public class tugas2 extends javax.swing.JFrame {
    private String makanan,qty;
    private int harga, jumlah, total;
    /**
     * Creates new form tugas2
     */
    public tugas2() {
        initComponents();
        tombolmin.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        tombolplus = new javax.swing.JButton();
        tombolmin = new javax.swing.JButton();
        tombolbeli = new javax.swing.JButton();
        tombolhapus = new javax.swing.JButton();
        enasirames = new javax.swing.JRadioButton();
        eayamgeprek = new javax.swing.JRadioButton();
        esoto = new javax.swing.JRadioButton();
        ebebekgoreng = new javax.swing.JRadioButton();
        enasipecel = new javax.swing.JRadioButton();
        ebakso = new javax.swing.JRadioButton();
        elelegoreng = new javax.swing.JRadioButton();
        eikanbakar = new javax.swing.JRadioButton();
        emieayam = new javax.swing.JRadioButton();
        ebebeksinjay = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lqty = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Lpesanan = new javax.swing.JLabel();
        Lharga = new javax.swing.JLabel();
        Ljumlah = new javax.swing.JLabel();
        Ltotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tombolplus.setText("+");
        tombolplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolplusActionPerformed(evt);
            }
        });
        getContentPane().add(tombolplus);
        tombolplus.setBounds(80, 320, 40, 23);

        tombolmin.setText("-");
        tombolmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolminActionPerformed(evt);
            }
        });
        getContentPane().add(tombolmin);
        tombolmin.setBounds(80, 360, 40, 23);

        tombolbeli.setText("BELI");
        tombolbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolbeliActionPerformed(evt);
            }
        });
        getContentPane().add(tombolbeli);
        tombolbeli.setBounds(180, 320, 84, 23);

        tombolhapus.setText("HAPUS");
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });
        getContentPane().add(tombolhapus);
        tombolhapus.setBounds(180, 360, 84, 23);

        buttonGroup1.add(enasirames);
        enasirames.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        enasirames.setForeground(java.awt.Color.white);
        enasirames.setText("Nasi Rames");
        enasirames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enasiramesActionPerformed(evt);
            }
        });
        getContentPane().add(enasirames);
        enasirames.setBounds(30, 180, 120, 23);

        buttonGroup1.add(eayamgeprek);
        eayamgeprek.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        eayamgeprek.setForeground(new java.awt.Color(255, 255, 255));
        eayamgeprek.setText("Ayam Geprek");
        eayamgeprek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eayamgeprekActionPerformed(evt);
            }
        });
        getContentPane().add(eayamgeprek);
        eayamgeprek.setBounds(30, 140, 130, 23);

        buttonGroup1.add(esoto);
        esoto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        esoto.setForeground(java.awt.Color.white);
        esoto.setText("Soto");
        esoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esotoActionPerformed(evt);
            }
        });
        getContentPane().add(esoto);
        esoto.setBounds(580, 180, 80, 23);

        buttonGroup1.add(ebebekgoreng);
        ebebekgoreng.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ebebekgoreng.setForeground(java.awt.Color.white);
        ebebekgoreng.setText("Bebek Goreng");
        ebebekgoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebebekgorengActionPerformed(evt);
            }
        });
        getContentPane().add(ebebekgoreng);
        ebebekgoreng.setBounds(160, 140, 140, 23);

        buttonGroup1.add(enasipecel);
        enasipecel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        enasipecel.setForeground(java.awt.Color.white);
        enasipecel.setText("Nasi Pecel");
        enasipecel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enasipecelActionPerformed(evt);
            }
        });
        getContentPane().add(enasipecel);
        enasipecel.setBounds(160, 180, 120, 23);

        buttonGroup1.add(ebakso);
        ebakso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ebakso.setForeground(java.awt.Color.white);
        ebakso.setText("Bakso");
        ebakso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebaksoActionPerformed(evt);
            }
        });
        getContentPane().add(ebakso);
        ebakso.setBounds(580, 140, 100, 23);

        buttonGroup1.add(elelegoreng);
        elelegoreng.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        elelegoreng.setForeground(java.awt.Color.white);
        elelegoreng.setText("Lele Goreng");
        elelegoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elelegorengActionPerformed(evt);
            }
        });
        getContentPane().add(elelegoreng);
        elelegoreng.setBounds(310, 140, 110, 23);

        buttonGroup1.add(eikanbakar);
        eikanbakar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        eikanbakar.setForeground(java.awt.Color.white);
        eikanbakar.setText("Ikan Bakar");
        eikanbakar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eikanbakarActionPerformed(evt);
            }
        });
        getContentPane().add(eikanbakar);
        eikanbakar.setBounds(310, 180, 110, 23);

        buttonGroup1.add(emieayam);
        emieayam.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        emieayam.setForeground(java.awt.Color.white);
        emieayam.setText("Mie Ayam");
        emieayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emieayamActionPerformed(evt);
            }
        });
        getContentPane().add(emieayam);
        emieayam.setBounds(440, 180, 100, 23);

        buttonGroup1.add(ebebeksinjay);
        ebebeksinjay.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        ebebeksinjay.setForeground(java.awt.Color.white);
        ebebeksinjay.setText("Bebek Sinjay");
        ebebeksinjay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ebebeksinjayActionPerformed(evt);
            }
        });
        getContentPane().add(ebebeksinjay);
        ebebeksinjay.setBounds(440, 140, 120, 23);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Warung Tay-Nyantay");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 250, 47);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Aneka Makanan   :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 160, 18);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 330, 0, 0);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\" Sajian Lezat di setiap Gigitan, Warung Makan Berkualitas, Harga Bersahabat\"");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 250, 540, 21);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Beli :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 300, 100, 18);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Pesanan     :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 320, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Harga         :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 360, 90, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Jumlah  :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(510, 320, 70, 17);

        lqty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lqty.setForeground(new java.awt.Color(255, 255, 255));
        lqty.setText("0");
        getContentPane().add(lqty);
        lqty.setBounds(140, 330, 20, 48);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Total      :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(510, 360, 70, 17);

        Lpesanan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lpesanan.setForeground(java.awt.Color.white);
        getContentPane().add(Lpesanan);
        Lpesanan.setBounds(384, 320, 120, 22);

        Lharga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Lharga.setForeground(java.awt.Color.white);
        getContentPane().add(Lharga);
        Lharga.setBounds(390, 360, 110, 22);

        Ljumlah.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ljumlah.setForeground(java.awt.Color.white);
        getContentPane().add(Ljumlah);
        Ljumlah.setBounds(580, 320, 90, 22);

        Ltotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ltotal.setForeground(java.awt.Color.white);
        getContentPane().add(Ltotal);
        Ltotal.setBounds(580, 360, 90, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\11zon_resized.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 700, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enasiramesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enasiramesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enasiramesActionPerformed

    private void eayamgeprekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eayamgeprekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eayamgeprekActionPerformed

    private void esotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esotoActionPerformed

    private void ebebekgorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebebekgorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebebekgorengActionPerformed

    private void enasipecelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enasipecelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enasipecelActionPerformed

    private void ebaksoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebaksoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebaksoActionPerformed

    private void elelegorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elelegorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elelegorengActionPerformed

    private void eikanbakarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eikanbakarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eikanbakarActionPerformed

    private void emieayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emieayamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emieayamActionPerformed

    private void ebebeksinjayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ebebeksinjayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ebebeksinjayActionPerformed

    private void tombolplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolplusActionPerformed
        // TODO add your handling code here:
        qty = lqty.getText();
        if ("0".equals(qty)) {
            tombolmin.setEnabled(true);
        }
        jumlah = Integer.parseInt(qty);
        jumlah = jumlah + 1;
        lqty.setText(String.valueOf(jumlah));
    }//GEN-LAST:event_tombolplusActionPerformed

    private void tombolminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolminActionPerformed
        // TODO add your handling code here:
        qty = lqty.getText();
        if ("1".equals(qty)) {
            tombolmin.setEnabled(false);
        }
        jumlah = Integer.parseInt(qty);
        jumlah = jumlah - 1;
        lqty.setText(String.valueOf(jumlah));
    
    }//GEN-LAST:event_tombolminActionPerformed

    private void tombolbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolbeliActionPerformed
        // TODO add your handling code here:
        if (eayamgeprek.isSelected()) {
            makanan = "Ayam Geprek";
            harga = 10000;
        }else if (enasirames.isSelected()) {
            makanan = "Nasi Rames";
            harga = 7000;
        }else if (esoto.isSelected()) {
            makanan = "Soto";
            harga = 8000;
        }else if (ebebekgoreng.isSelected()) {
            makanan = "Bebek Goreng";
            harga = 15000;
        }else if (enasipecel.isSelected()) {
            makanan = "Nasi Pecel";
            harga = 9000;
        }else if (ebakso.isSelected()) {
            makanan = "Bakso";
            harga = 10000;
        }else if (elelegoreng.isSelected()) {
            makanan = "Lele Goreng";
            harga = 10000;
        }else if (eikanbakar.isSelected()) {
            makanan = "Ikan Bakar";
            harga = 20000;
        }else if (emieayam.isSelected()) {
            makanan = "Mie Ayam";
            harga = 8000;
        }
//        JOptionPane.showMessageDialog(this, "Berhasil Memesan");
        Lpesanan.setText(makanan);
        Lharga.setText(String.valueOf(harga));
        Ljumlah.setText(lqty.getText());
        jumlah = Integer.parseInt(lqty.getText());
        total = harga * jumlah;
        Ltotal.setText(String.valueOf(total));

         JOptionPane.showMessageDialog(this, "Silahkan Pilih Menu!");
         return;
    }//GEN-LAST:event_tombolbeliActionPerformed

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        // TODO add your handling code here:
        buttonGroup1.clearSelection();
        lqty.setText("0");
        Lpesanan.setText("-");
        Lharga.setText("-");
        Ljumlah.setText("-");
        Ltotal.setText("-");
        tombolmin.setEnabled(false);
    }//GEN-LAST:event_tombolhapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lharga;
    private javax.swing.JLabel Ljumlah;
    private javax.swing.JLabel Lpesanan;
    private javax.swing.JLabel Ltotal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JRadioButton eayamgeprek;
    private javax.swing.JRadioButton ebakso;
    private javax.swing.JRadioButton ebebekgoreng;
    private javax.swing.JRadioButton ebebeksinjay;
    private javax.swing.JRadioButton eikanbakar;
    private javax.swing.JRadioButton elelegoreng;
    private javax.swing.JRadioButton emieayam;
    private javax.swing.JRadioButton enasipecel;
    private javax.swing.JRadioButton enasirames;
    private javax.swing.JRadioButton esoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lqty;
    private javax.swing.JButton tombolbeli;
    private javax.swing.JButton tombolhapus;
    private javax.swing.JButton tombolmin;
    private javax.swing.JButton tombolplus;
    // End of variables declaration//GEN-END:variables
}
