/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum_2;

/**
 *
 * @author User
 */
public class tugas1 extends javax.swing.JFrame {

    /**
     * Creates new form tugas1
     */
    public tugas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jumlahjamkerja = new javax.swing.JTextField();
        tarifperjam = new javax.swing.JTextField();
        gajibruto = new javax.swing.JTextField();
        gajibersih = new javax.swing.JTextField();
        hitungbruto = new javax.swing.JButton();
        hitungbersih = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 18)); // NOI18N
        jLabel1.setText("Penghitung Gaji Karyawan");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(185, 6, 280, 24);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel2.setText("Jumlah Jam Kerja 1 Minggu :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 80, 172, 15);

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel3.setText("Tarif per-Jam                           :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 145, 180, 15);

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel4.setText("Gaji Bruto                                :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 216, 170, 15);

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel5.setText("Gaji Bersih                              :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(6, 281, 180, 15);
        getContentPane().add(jumlahjamkerja);
        jumlahjamkerja.setBounds(196, 76, 258, 30);

        tarifperjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifperjamActionPerformed(evt);
            }
        });
        getContentPane().add(tarifperjam);
        tarifperjam.setBounds(194, 141, 260, 30);
        getContentPane().add(gajibruto);
        gajibruto.setBounds(191, 216, 263, 30);
        getContentPane().add(gajibersih);
        gajibersih.setBounds(190, 280, 263, 30);

        hitungbruto.setText("Hitung Gaji Bruto");
        hitungbruto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbrutoActionPerformed(evt);
            }
        });
        getContentPane().add(hitungbruto);
        hitungbruto.setBounds(490, 220, 128, 23);

        hitungbersih.setText("Hutung Gaji Bersih");
        hitungbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungbersihActionPerformed(evt);
            }
        });
        getContentPane().add(hitungbersih);
        hitungbersih.setBounds(490, 280, 129, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/praktikum_2/bg kantor (1).jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 650, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tarifperjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifperjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifperjamActionPerformed

    private void hitungbrutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbrutoActionPerformed
        // TODO add your handling code here:
        double jumlahJamKerja = Double.parseDouble(jumlahjamkerja.getText());
        double tarifPerJam = Double.parseDouble(tarifperjam.getText());

        // Menghitung gaji bruto
        double gajiBruto;
        if (jumlahJamKerja > 40) {
            // Jika jam kerja lebih dari 40, hitung lembur dengan tarif 1.5 kali lipat
            double jamLembur = jumlahJamKerja - 40;
            gajiBruto = (40 * tarifPerJam) + (jamLembur * 1.5 * tarifPerJam);
        } else {
            // Jika jam kerja tidak lebih dari 40, hitung tanpa lembur
            gajiBruto = jumlahJamKerja * tarifPerJam;
        }

        // Menampilkan gaji bruto di JTextField3
        gajibruto.setText(String.valueOf(gajiBruto));
    }//GEN-LAST:event_hitungbrutoActionPerformed

    private void hitungbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungbersihActionPerformed
        // TODO add your handling code here:
        double gajiBruto = Double.parseDouble(gajibruto.getText());

        // Menghitung gaji bersih (gaji bruto dikali 10%)
        double gajiBersih = gajiBruto - (gajiBruto * 0.10 );

        // Menampilkan gaji bersih di JTen nxtField4
        gajibersih.setText(String.valueOf(gajiBersih));
    }//GEN-LAST:event_hitungbersihActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField gajibersih;
    private javax.swing.JTextField gajibruto;
    private javax.swing.JButton hitungbersih;
    private javax.swing.JButton hitungbruto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jumlahjamkerja;
    private javax.swing.JTextField tarifperjam;
    // End of variables declaration//GEN-END:variables
}
